In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In lasso regression we try to shrick some weights exactly to zero if w>1 we use +1 if w==0 wwe use 0 else we use -1

In [4]:
class LassoRegression:
    def __init__(self, lr=0.01, n_iters=1000,alpha=0.1):
        self.lr = lr
        self.n_iters = n_iters
        self.alpha=alpha
        self.weights = None
        self.bias = 0

    def fit(self, X, y):
        n_samples,n_features=X.shape
        self.weights=np.zeros(n_features)
        self.bias=0
        for _ in range(self.n_iters):
            y_pred=np.dot(X,self.weights)+self.bias

            dw=(1/n_samples)*np.dot(X.T,(y_pred-y))+self.alpha*np.sign(self.weights)
            db=(1/n_samples)*np.sum(y_pred-y)

            self.weights-=self.lr*dw
            self.bias-=self.lr*db
            print(self.weights)

    def predict(self,X):
        return np.dot(X,self.weights)+self.bias

    def mse(self,y_true,y_pred):
        return np.mean((y_true-y_pred)**2)

In [5]:
from sklearn.linear_model import Lasso
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [6]:
X,y=make_regression(n_samples=300,n_features=5,n_informative=3,noise=20,random_state=42)

In [10]:
lasso=LassoRegression(lr=0.01,n_iters=1000,alpha=0.1)
lasso.fit(X,y)

[0.0465858  0.11706696 0.48214729 0.92589995 0.28036025]
[0.09134528 0.2306058  0.95862904 1.84012572 0.55675612]
[0.13530025 0.34166869 1.43050225 2.74381445 0.83022945]
[0.17846224 0.45029563 1.89781266 3.63708899 1.10081123]
[0.22084265 0.55652602 2.36060555 4.52007072 1.36853215]
[0.26245272 0.66039872 2.81892573 5.39287963 1.63342253]
[0.30330356 0.76195202 3.27281753 6.25563427 1.89551241]
[0.34340612 0.86122363 3.72232487 7.1084518  2.15483149]
[0.38277119 0.95825075 4.1674912  7.95144802 2.41140914]
[0.42140945 1.05307003 4.60835951 8.78473735 2.66527444]
[0.45933142 1.14571756 5.04497239 9.60843286 2.91645615]
[ 0.49654749  1.23622894  5.47737197 10.4226463   3.16498272]
[ 0.53306791  1.32463924  5.90559996 11.22748812  3.41088231]
[ 0.56890278  1.41098302  6.32969764 12.02306745  3.65418275]
[ 0.60406209  1.49529433  6.74970587 12.80949214  3.89491161]
[ 0.6385557   1.57760673  7.1656651  13.58686879  4.13309614]
[ 0.67239331  1.6579533   7.57761537 14.35530271  4.36876331]
[

In [11]:
lasso.mse(y,lasso.predict(X))

np.float64(369.9983490773717)

In [42]:
lasso.weights

array([ 0.72562138, -0.53899794, 50.86190018, 81.36321989, 26.41378398])

In [3]:
np.sign(-1)

np.int64(-1)

In [43]:
model=Lasso(alpha=0.1)
model.fit(X,y)


Lasso(alpha=0.1)

In [44]:
from sklearn.metrics import mean_squared_error

In [45]:
mean_squared_error(y,model.predict(X))

369.99590914528227

In [46]:
model.coef_

array([ 0.72561414, -0.53900344, 50.86190176, 81.3632206 , 26.41378433])